export const students = [
    {
      id: "1",
      name: "John Doe",
      email: "john.doe@example.com",
      avatar: "",
      year: "Freshman",
      section: "A",
      age: 18,
      grade: 10,
      status: "Active",
      address: "123 Campus Drive, University City",
      birthdate: "2007-05-23",
      gender: "Male",
      ethnicity: "Caucasian",
      nationality: "American",
      religion: "Christian",
      orderNumber: "8547921",
      chronicDisease: "No Record",
      studentNumber: "STU2023001",
      yearGroup: "Year 10",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "2",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      avatar: "",
      year: "Sophomore",
      section: "B",
      age: 19,
      grade: 11,
      status: "Active",
      address: "456 College Ave, University City",
      birthdate: "2006-08-15",
      gender: "Female",
      ethnicity: "Asian",
      nationality: "Chinese",
      religion: "Buddhist",
      orderNumber: "8547922",
      chronicDisease: "No Record",
      studentNumber: "STU2023002",
      yearGroup: "Year 11",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "3",
      name: "David Lee",
      email: "david.lee@example.com",
      avatar: "",
      year: "Junior",
      section: "C",
      age: 20,
      grade: 12,
      status: "Active",
      address: "789 Student Lane, University City",
      birthdate: "2005-12-03",
      gender: "Male",
      ethnicity: "Asian",
      nationality: "Korean",
      religion: "Christian",
      orderNumber: "8547923",
      chronicDisease: "No Record",
      studentNumber: "STU2023003",
      yearGroup: "Year 12",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "4",
      name: "Emma Wilson",
      email: "emma.wilson@example.com",
      avatar: "",
      year: "Senior",
      section: "A",
      age: 21,
      grade: 12,
      status: "Active",
      address: "901 University Drive, University City",
      birthdate: "2004-09-12",
      gender: "Female",
      ethnicity: "Caucasian",
      nationality: "British",
      religion: "Christian",
      orderNumber: "8547924",
      chronicDisease: "Asthma",
      studentNumber: "STU2023004",
      yearGroup: "Year 12",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "5",
      name: "Michael Chen",
      email: "michael.chen@example.com",
      avatar: "",
      year: "Freshman",
      section: "B",
      age: 18,
      grade: 10,
      status: "Inactive",
      address: "234 Student Street, University City",
      birthdate: "2007-03-28",
      gender: "Male",
      ethnicity: "Asian",
      nationality: "Chinese",
      religion: "Buddhist",
      orderNumber: "8547925",
      chronicDisease: "No Record",
      studentNumber: "STU2023005",
      yearGroup: "Year 10",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "6",
      name: "Sofia Rodriguez",
      email: "sofia.rodriguez@example.com",
      avatar: "",
      year: "Sophomore",
      section: "C",
      age: 19,
      grade: 11,
      status: "Active",
      address: "567 College Court, University City",
      birthdate: "2006-11-15",
      gender: "Female",
      ethnicity: "Hispanic",
      nationality: "Mexican",
      religion: "Catholic",
      orderNumber: "8547926",
      chronicDisease: "No Record",
      studentNumber: "STU2023006",
      yearGroup: "Year 11",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "7",
      name: "Ahmed Hassan",
      email: "ahmed.hassan@example.com",
      avatar: "",
      year: "Junior",
      section: "A",
      age: 20,
      grade: 12,
      status: "Active",
      address: "890 University Avenue, University City",
      birthdate: "2005-07-20",
      gender: "Male",
      ethnicity: "Middle Eastern",
      nationality: "Egyptian",
      religion: "Muslim",
      orderNumber: "8547927",
      chronicDisease: "Diabetes Type 1",
      studentNumber: "STU2023007",
      yearGroup: "Year 12",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "8",
      name: "Isabella Kumar",
      email: "isabella.kumar@example.com",
      avatar: "",
      year: "Senior",
      section: "B",
      age: 21,
      grade: 12,
      status: "Inactive",
      address: "345 Student Way, University City",
      birthdate: "2004-04-05",
      gender: "Female",
      ethnicity: "South Asian",
      nationality: "Indian",
      religion: "Hindu",
      orderNumber: "8547928",
      chronicDisease: "No Record",
      studentNumber: "STU2023008",
      yearGroup: "Year 12",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "9",
      name: "Lucas Silva",
      email: "lucas.silva@example.com",
      avatar: "",
      year: "Freshman",
      section: "C",
      age: 18,
      grade: 10,
      status: "Active",
      address: "678 College Boulevard, University City",
      birthdate: "2007-08-30",
      gender: "Male",
      ethnicity: "Hispanic",
      nationality: "Brazilian",
      religion: "Catholic",
      orderNumber: "8547929",
      chronicDisease: "No Record",
      studentNumber: "STU2023009",
      yearGroup: "Year 10",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "10",
      name: "Olivia Park",
      email: "olivia.park@example.com",
      avatar: "",
      year: "Sophomore",
      section: "A",
      age: 19,
      grade: 11,
      status: "Inactive",
      address: "901 Student Road, University City",
      birthdate: "2006-01-25",
      gender: "Female",
      ethnicity: "Asian",
      nationality: "Korean",
      religion: "Buddhist",
      orderNumber: "8547930",
      chronicDisease: "Allergies",
      studentNumber: "STU2023010",
      yearGroup: "Year 11",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "11",
      name: "William Thompson",
      email: "william.thompson@example.com",
      avatar: "",
      year: "Junior",
      section: "B",
      age: 20,
      grade: 12,
      status: "Active",
      address: "234 University Street, University City",
      birthdate: "2005-05-17",
      gender: "Male",
      ethnicity: "Caucasian",
      nationality: "Canadian",
      religion: "Christian",
      orderNumber: "8547931",
      chronicDisease: "No Record",
      studentNumber: "STU2023011",
      yearGroup: "Year 12",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
    {
      id: "12",
      name: "Ava Nguyen",
      email: "ava.nguyen@example.com",
      avatar: "",
      year: "Senior",
      section: "C",
      age: 21,
      grade: 12,
      status: "Active",
      address: "567 Student Drive, University City",
      birthdate: "2004-12-08",
      gender: "Female",
      ethnicity: "Asian",
      nationality: "Vietnamese",
      religion: "Buddhist",
      orderNumber: "8547932",
      chronicDisease: "No Record",
      studentNumber: "STU2023012",
      yearGroup: "Year 12",
      guardians: [
          {
              name: "Alice Doe",
              relationship: "Mother",
              phone: "123-456-7890",
          },
          {
              name: "Bob Doe",
              relationship: "Father",
              phone: "098-765-4321",
          }
      ],
      guardianName: "Guardian Name",
      guardianRelationship: "Relationship",
      guardianPhone: "123-456-7890",
      guardianEmail: "guardian@example.com",
      guardianAddress: "123 Guardian St, University City",
    },
  ]